import tests.threads.CountdownThreadTest
import tests.threads.InitiateTuyaAnalyticsThreadTest
import tests.threads.InitiateTuyaManagerThreadTest
import tests.threads.InitiateTuyaSchedulesManagerThreadTest
import tests.threads.InitiateTuyaSmartModeThreadTest