import tests.gui.all_devices.AllDevicesWidgetTest
import tests.gui.analytics.AnalyticsWidgetTest
import tests.gui.credentials.CredentialsWidgetTest
import tests.gui.device.BulbNameLabelTest
import tests.gui.device.BulbSwitchButtonTest
import tests.gui.device.DeviceWidgetTest
import tests.gui.device.tabs.ColourModeTabTest
import tests.gui.device.tabs.CountdownTabTest
import tests.gui.device.tabs.WhiteModeTabTest
import tests.gui.help.HelpWidgetTest
import tests.gui.profile.ProfileWidgetTest
import tests.gui.schedules.EditScheduleWidgetTest
import tests.gui.schedules.SchedulesWidgetTest
import tests.gui.settings.SettingsWidgetTest
import tests.gui.smart_mode.SmartModeWidgetTest
import tests.gui.tools.ClearLayoutTest
import tests.gui.tools.ShowErrorToastTest
import tests.gui.ActionBarLayoutTest
import tests.gui.MainLayoutTest
import tests.gui.MainWindowTest
import tests.gui.NavigationBarLayoutTest
import tests.gui.StackedWidgetTest