from PyQt6.QtGui import QIcon
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QSizePolicy, QToolButton, QFrame, QVBoxLayout

class NavigationBarLayout(QVBoxLayout):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.setProperty("class", "navigation_bar")
        self.setContentsMargins(10, 10, 0, 10)

        self.pushbutton_devices = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_devices.sizePolicy().hasHeightForWidth())
        self.pushbutton_devices.setSizePolicy(sizePolicy)
        self.pushbutton_devices.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.pushbutton_devices.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushbutton_devices.setIcon(QIcon(":/navigation/devices.png"))
        self.pushbutton_devices.setCheckable(False)
        self.pushbutton_devices.setProperty("class", "tab_button")
        self.pushbutton_devices.setText("DEVICES")
        self.pushbutton_devices.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.pushbutton_devices.setArrowType(Qt.ArrowType.NoArrow)
        self.addWidget(self.pushbutton_devices)

        self.line = QFrame()
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.addWidget(self.line)

        self.pushbutton_scenes = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_scenes.sizePolicy().hasHeightForWidth())
        self.pushbutton_scenes.setSizePolicy(sizePolicy)
        self.pushbutton_scenes.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.pushbutton_scenes.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushbutton_scenes.setIcon(QIcon(":/navigation/scenes.png"))
        self.pushbutton_scenes.setCheckable(False)
        self.pushbutton_scenes.setProperty("class", "tab_button")
        self.pushbutton_scenes.setText("SCENES")
        self.pushbutton_scenes.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.pushbutton_scenes.setArrowType(Qt.ArrowType.NoArrow)
        self.addWidget(self.pushbutton_scenes)

        self.line_2 = QFrame()
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.addWidget(self.line_2)

        self.pushbutton_analytics = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_analytics.sizePolicy().hasHeightForWidth())
        self.pushbutton_analytics.setSizePolicy(sizePolicy)
        self.pushbutton_analytics.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.pushbutton_analytics.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushbutton_analytics.setIcon(QIcon(":/navigation/analytics.png"))
        self.pushbutton_analytics.setCheckable(False)
        self.pushbutton_analytics.setProperty("class", "tab_button")
        self.pushbutton_analytics.setText("ANALYTICS")
        self.pushbutton_analytics.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.pushbutton_analytics.setArrowType(Qt.ArrowType.NoArrow)
        self.addWidget(self.pushbutton_analytics)

        self.line_3 = QFrame()
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.addWidget(self.line_3)

        self.pushbutton_schedule = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_schedule.sizePolicy().hasHeightForWidth())
        self.pushbutton_schedule.setSizePolicy(sizePolicy)
        self.pushbutton_schedule.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.pushbutton_schedule.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushbutton_schedule.setIcon(QIcon(":/navigation/schedule.png"))
        self.pushbutton_schedule.setCheckable(False)
        self.pushbutton_schedule.setProperty("class", "tab_button")
        self.pushbutton_schedule.setText("SCHEDULE")
        self.pushbutton_schedule.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.pushbutton_schedule.setArrowType(Qt.ArrowType.NoArrow)
        self.addWidget(self.pushbutton_schedule)