from PyQt6.QtCore import Qt
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QSizePolicy, QToolButton, QFrame, QVBoxLayout, QButtonGroup

from modules.dictionaries.loader import load_dictionary


class NavigationBarLayout(QVBoxLayout):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.setProperty("class", "navigation_bar")
        self.setContentsMargins(10, 10, 0, 10)

        self.dictionary = load_dictionary()

        self.button_group = QButtonGroup()

        self.devices_button = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devices_button.sizePolicy().hasHeightForWidth())
        self.devices_button.setSizePolicy(sizePolicy)
        self.devices_button.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.devices_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.devices_button.setIcon(QIcon(":/navigation/devices.png"))
        self.devices_button.setProperty("class", "tab_button")
        self.devices_button.setText(self.dictionary["devices"])
        self.devices_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.devices_button.setArrowType(Qt.ArrowType.NoArrow)
        self.devices_button.setCheckable(True)
        self.button_group.addButton(self.devices_button)
        self.addWidget(self.devices_button)

        self.line = QFrame()
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.addWidget(self.line)

        self.scenes_button = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenes_button.sizePolicy().hasHeightForWidth())
        self.scenes_button.setSizePolicy(sizePolicy)
        self.scenes_button.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.scenes_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.scenes_button.setIcon(QIcon(":/navigation/scenes.png"))
        self.scenes_button.setProperty("class", "tab_button")
        self.scenes_button.setText(self.dictionary["scenes"])
        self.scenes_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.scenes_button.setArrowType(Qt.ArrowType.NoArrow)
        self.scenes_button.setCheckable(True)
        self.button_group.addButton(self.scenes_button)
        self.addWidget(self.scenes_button)

        self.line_2 = QFrame()
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.addWidget(self.line_2)

        self.analytics_button = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analytics_button.sizePolicy().hasHeightForWidth())
        self.analytics_button.setSizePolicy(sizePolicy)
        self.analytics_button.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.analytics_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.analytics_button.setIcon(QIcon(":/navigation/analytics.png"))
        self.analytics_button.setProperty("class", "tab_button")
        self.analytics_button.setText(self.dictionary["analytics"])
        self.analytics_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.analytics_button.setArrowType(Qt.ArrowType.NoArrow)
        self.analytics_button.setCheckable(True)
        self.button_group.addButton(self.analytics_button)
        self.addWidget(self.analytics_button)

        self.line_3 = QFrame()
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.addWidget(self.line_3)

        self.schedule_button = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_button.sizePolicy().hasHeightForWidth())
        self.schedule_button.setSizePolicy(sizePolicy)
        self.schedule_button.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.schedule_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.schedule_button.setIcon(QIcon(":/navigation/schedule.png"))
        self.schedule_button.setProperty("class", "tab_button")
        self.schedule_button.setText(self.dictionary["schedule"])
        self.schedule_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.schedule_button.setArrowType(Qt.ArrowType.NoArrow)
        self.schedule_button.setCheckable(True)
        self.button_group.addButton(self.schedule_button)
        self.addWidget(self.schedule_button)

        self.line_4 = QFrame()
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.addWidget(self.line_4)

        self.help_button = QToolButton()
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.help_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.help_button.setIcon(QIcon(":/navigation/help.png"))
        self.help_button.setProperty("class", "tab_button")
        self.help_button.setText(self.dictionary["help"])
        self.help_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.help_button.setArrowType(Qt.ArrowType.NoArrow)
        self.help_button.setCheckable(True)
        self.button_group.addButton(self.help_button)
        self.addWidget(self.help_button)
